config/routes.rb
Rails.application.routes.draw do
 root to: "toppages#index"
 
 get "login", to: "sessions#new"
 post "login", to: "sessions#create"
 delete "logout", to: "sessions#destroy"

 get "signup", to: "users#new"
 resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
 resources :reports, only: [:new, :create, :show, :edit, :update, :destroy]
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  before_action :reportlist
  
  def index
    if logged_in?
      @reports = current_user.reports.order(id: :desc).page(params[:page]).per(25)
    end
  end
  
  def reportlist
    if logged_in?
      @reportlist_1 = current_user.reports.where(["day >= :day_s and day < :day_e", {day_s: current_user.entrance_year * 10000 + 401, day_e: current_user.entrance_year * 10000 + 10401}])
      @reportlist_2 = current_user.reports.where(["day >= :day_s and day < :day_e", {day_s: current_user.entrance_year * 10000 + 10401, day_e: current_user.entrance_year * 10000 + 20401}])
      @reportlist_3 = current_user.reports.where(["day >= :day_s and day < :day_e", {day_s: current_user.entrance_year * 10000 + 20401, day_e: current_user.entrance_year * 10000 + 30401}])
      @reportlist_4 = current_user.reports.where(["day >= :day_s and day < :day_e", {day_s: current_user.entrance_year * 10000 + 30401, day_e: current_user.entrance_year * 10000 + 40401}])
    end
  end
end

app/views/toppages/index.html.erb
<% if logged_in? %>
  <div class="container cs-container2 mt-4">
  <%= render "layouts/flash_messages" %>
    <div class="row cs-box2 mt-4">
      <%= render "layouts/aside" %>
      <div class="col-sm-8">
        <div class="cs-white p-4 mb-4">
          <h1 class="text-center"><%= link_to "レポートを登録!", new_report_path %></h1>
        </div>
        <div class="cs-white p-3">
          <h1 class="text-center mb-3">レポート一覧</h1>
          <ul>
            <% @reports.each do |report| %>
              <li class="mb-3">
                <%= link_to report.title, report_path(report), class: "report" %>
                <%= link_to "delete", report, method: :delete, data: { confirm: "本当によろしいですか?" }, class: "btn btn-outline-danger btn-sm cs-delete" %>
                <%= link_to "pdf", url_for(report.repo), class: "btn btn-outline-info btn-sm cs-pdf" %>
              </li>
            <% end %>
          </ul>
          <%= paginate @reports %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="mb-0">
    <%= render "layouts/flash_messages" %>
  </div>
  <div class="cs-unlogin">
    <div class="cs-box">
      <h1 class="text-center cs-text1">Welcome To The Reportlist</h1>
      <p class="text-center cs-text2 mt-3">Reportlistはレポートをネット上で管理するためのサイトです。</p>
      <div class="cs-login-buttons">
        <div class="cs-button-box">
          <%= link_to "ログイン！", login_path, class: "cs-login-button" %>
        </div>
        <div class="cs-signup">
          <p class="cs-text3">アカウントをお持ちでない方:</p>
          <%= link_to "新規登録", signup_path, class: "cs-signup-button btn btn-light" %>
        </div>
      </div>
    </div>
  </div>
<% end %>