config/routes.rb
Rails.application.routes.draw do
 root to: "toppages#index"
 
 get "login", to: "sessions#new"
 post "login", to: "sessions#create"
 delete "logout", to: "sessions#destroy"

 get "signup", to: "users#new"
 resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
 resources :reports, only: [:new, :create, :show, :edit, :update, :destroy]
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
  
  has_one_attached :repo
  

  validates :title, presence: true, length: { maximum: 50 }
  validates :day, presence: true, length: { is: 8 }
  validates :teaching, length: { maximum: 50 }
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :require_user_logged_in
  before_action :data, only: [:new, :create, :edit, :update]
  before_action :correct_user?, only: [:show, :edit, :update, :destroy]
  before_action :reportlist, only: [:show, :new, :edit]
  
  def new
    @report = current_user.reports.build
  end

  def create
    report_params2 = report_params
    report_params2[:day] = report_params[:day_y].to_i * 10000 + report_params[:day_m].to_i * 100 + report_params[:day_d].to_i
    report_params2.delete(:day_y)
    report_params2.delete(:day_m)
    report_params2.delete(:day_d)
    

    @report = current_user.reports.build(report_params2)
    if @report.save
      flash[:success] = "登録しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "登録に失敗しました。"
      render :new
    end
    
    
  end

  def show
  end

  def edit
    day_fy = @report.day / 10000
    selected_y = {name_y: day_fy.to_s + "年", id_y: day_fy}
    @year.unshift(selected_y)
    
    day_fm = (@report.day - (@report.day / 10000) * 10000) / 100
    selected_m = {name_m: day_fm.to_s + "月", id_m: day_fm}
    @month.unshift(selected_m)
    
    day_fd = (@report.day - (@report.day / 100) * 100)
    selected_d = {name_d: day_fd.to_s + "日", id_d: day_fd}
    @day.unshift(selected_d)
  end

  def update
    report_params2 = report_params
    report_params2[:day] = report_params[:day_y].to_i * 10000 + report_params[:day_m].to_i * 100 + report_params[:day_d].to_i
    report_params2.delete(:day_y)
    report_params2.delete(:day_m)
    report_params2.delete(:day_d)
    
    if  @report.update(report_params2)
      flash[:success] = "レポートを編集しました。"
      redirect_to root_url
    else
      flash.now[:danger] = "レポートの編集に失敗しました。"
      render :edit 
    end
  end

  

  def destroy
    @report.destroy
    flash[:success] = "レポートを削除しました。"
    redirect_to root_url
  end
  
  private
  
  def report_params
    params.require(:report).permit(:repo, :title, :day_y, :day_m, :day_d, :teaching)
  end
  
  def data
    @year = [] 
    (2000..2030).each do |num|
      add = {name_y: num.to_s + "年", id_y: num}
      @year.push(add)
    end
    
    @month = []
    (1..12).each do |num|
      add = {name_m: num.to_s + "月", id_m: num}
      @month.push(add)
    end
    
    @day = []
    (1..31).each do |num|
      add = {name_d: num.to_s + "日", id_d: num}
      @day.push(add)
    end
  end
  
  def correct_user?
    @report = current_user.reports.find_by(id: params[:id])
    unless @report
      redirect_to root_url
    end
  end
  
  def reportlist
    reportlist_1 = current_user.reports.where(["day >= :day_s and day < :day_e", {day_s: current_user.entrance_year * 10000 + 401, day_e: current_user.entrance_year * 10000 + 10401}])
    reportlist_2 = current_user.reports.where(["day >= :day_s and day < :day_e", {day_s: current_user.entrance_year * 10000 + 10401, day_e: current_user.entrance_year * 10000 + 20401}])
    reportlist_3 = current_user.reports.where(["day >= :day_s and day < :day_e", {day_s: current_user.entrance_year * 10000 + 20401, day_e: current_user.entrance_year * 10000 + 30401}])
    reportlist_4 = current_user.reports.where(["day >= :day_s and day < :day_e", {day_s: current_user.entrance_year * 10000 + 30401, day_e: current_user.entrance_year * 10000 + 40401}])
    @reportlist_1 = reportlist_1.order(:day)
    @reportlist_2 = reportlist_2.order(:day)
    @reportlist_3 = reportlist_3.order(:day)
    @reportlist_4 = reportlist_4.order(:day)
  end
end

app/views/reports/edit.html.erb
<%= render "layouts/flash_messages" %>
  <div class="container cs-container2 mt-4">
    <div class="row cs-box2">
      <%= render "layouts/aside" %>
      <div class="col-sm-8">
        <div class="cs-white p-3">
          <h1 class="text-center mb-3">レポートを編集</h1>
          
          <%= form_with(model: @report, local: true) do |f| %>
            <%= render 'layouts/error_messages', model: f.object %>
            
            <div class="text-left text-sm-center">
              <div class="form-group row">
                <%= f.label :repo, "ファイル:", class: "col-sm-3 offset-sm-1 col-form-label" %>
                <%= f.file_field :repo, class: "form-control-file col-sm-6" %>
              </div>
              
              <div class="form-group row">
                <%= f.label :title, "タイトル:", class: "col-sm-3 offset-sm-1 col-form-label" %>
                <%= f.text_field :title, class: "form-control col-sm-6" %>
              </div>
              
              <div class="form-group row">
                <%= f.label :day, "実験日:", class: "col-sm-3 offset-sm-1 col-form-label" %>
                <%= f.select :day_y, options_for_select(@year.map{|c|[c[:name_y], c[:id_y]]},), {}, {class: 'mr-2'} %>
                <%= f.select :day_m, options_for_select(@month.map{|c|[c[:name_m], c[:id_m]]}), {}, {class: 'mr-2'} %>
                <%= f.select :day_d, options_for_select(@day.map{|c|[c[:name_d], c[:id_d]]}), {}, {} %>
              </div>
              
              <div class="form-group row">
                <%= f.label :teaching, "授業名", class: "col-sm-3 offset-sm-1 col-form-label" %>
                <%= f.text_field :teaching, class: "form-control col-sm-6" %>
              </div>
              
              <%= f.submit "編集",class: "btn btn-primary btn-block col-sm-3 offset-sm-4" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/reports/new.html.erb
<%= render "layouts/flash_messages" %>
  <div class="container cs-container2 mt-4">
    <div class="row cs-box2">
      <%= render "layouts/aside" %>
      <div class="col-sm-8">
        <div class="cs-white p-3">
          <h1 class="text-center mb-3">レポートを登録</h1>
          
          <%= form_with(model: @report, local: true) do |f| %>
            <%= render 'layouts/error_messages', model: f.object %>
            
            <div class="text-left text-sm-center">
              <div class="form-group row">
                <%= f.label :repo, "ファイル:", class: "col-sm-3 offset-sm-1 col-form-label" %>
                <%= f.file_field :repo, class: "form-control-file col-sm-6" %>
              </div>
              
              <div class="form-group row">
                <%= f.label :title, "タイトル:", class: "col-sm-3 offset-sm-1 col-form-label" %>
                <%= f.text_field :title, class: "form-control col-sm-6" %>
              </div>
              
              <div class="form-group row">
                <%= f.label :day, "実験日:", class: "col-sm-3 offset-sm-1 col-form-label" %>
                <%= f.select :day_y, options_for_select(@year.map{|c|[c[:name_y], c[:id_y]]}), {}, {class: 'mr-2'} %>
                <%= f.select :day_m, options_for_select(@month.map{|c|[c[:name_m], c[:id_m]]}), {}, {class: 'mr-2'} %>
                <%= f.select :day_d, options_for_select(@day.map{|c|[c[:name_d], c[:id_d]]}), {}, {} %>
              </div>
              
              <div class="form-group row">
                <%= f.label :teaching, "授業名", class: "col-sm-3 offset-sm-1 col-form-label" %>
                <%= f.text_field :teaching, class: "form-control col-sm-6" %>
              </div>
              
              <%= f.submit "登録",class: "btn btn-primary btn-block col-sm-3 offset-sm-4" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/reports/show.html.erb
<div class="container cs-container2 mt-4">
  <%= render "layouts/flash_messages" %>
  <div class="row cs-box2 mt-4">
    <%= render "layouts/aside" %>
    <div class="col-sm-8">
      <div class="cs-white p-4">
        <h1 class="text-center mb-3">レポート情報</h1>
        <table class="table">
          <tr>
            <th>タイトル</th>
            <td><%= @report.title %></td>
          </tr>
          <tr>
            <th>ファイル</th>
            <td><%= link_to "ファイル", url_for(@report.repo) %></td>
          </tr>
          <tr>
            <th>実験日</th>
            <td>
              <%= @report.day/10000 %>年
              <%= (@report.day - @report.day/10000*10000)/100 %>月
              <%= @report.day - @report.day/100*100 %>日
            </td>
          </tr>
          <tr>
            <th>授業名</th>
            <td><%= @report.teaching %></td>
          </tr>
        </table>
        <div class="mt-3">
          <%= link_to "編集する", edit_report_path, class: "cs-edit-button btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>