config/routes.rb
Rails.application.routes.draw do
 root to: "toppages#index"
 
 get "login", to: "sessions#new"
 post "login", to: "sessions#create"
 delete "logout", to: "sessions#destroy"

 get "signup", to: "users#new"
 resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
 resources :reports, only: [:new, :create, :show, :edit, :update, :destroy]
end

app/views/layouts/_aside.html.erb
<aside class="col-sm-4 mb-3 cs-container2">
  <div class="cs-white p-3">
    <h1 class="text-center">レポート</h1>
    <div class="hidden_box">
      <% if current_user.university == "東京工業大学" %>
        <% (1..4).each do |num| %>
          <div>
            <label for=<%= "label"+ num.to_s %>>大学<%= num.to_s %>年</label>
            <input type="checkbox" id=<%= "label" + num.to_s %>>
            <div class="hidden_show">
              <ul>
                <% eval("@reportlist = @reportlist_#{num}") %>
                <% unless @reportlist == nil %>
                  <% @reportlist.each do |report| %>
                    <li><%= link_to report.title, report_path(report) %></li>
                  <% end %>
                <% end %>
              </ul>
            </div>
          </div>
        <% end %>
      <% else %>
      <% end %>
　　</div>
  </div>
</aside>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> mb-0"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="cs-background">
  <div class="container">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark p-2">
      <a class="navbar-brand" href="/">Reprotlist</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>
      
      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
        <ul class="navbar-nav">
          <% if logged_in? %>
            <li class="nav-item"><%= link_to current_user.name, user_path(current_user), class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item"><%= link_to "新規登録", signup_path, class: "nav-link" %></li>
            <li class="nav-item"><%= link_to "ログイン", login_path, class: "nav-link" %></li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to -fit=no">
    <title>Reportlist</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <header>
      <%= render "layouts/navbar" %>
    </header>  
    <%= yield %>
  </body>
</html>